name: Make zk release

on:
  push:
    tags:
      - zk-v*
    branches:
      - docker

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.5"

      - name: "Run release script"
        run: cd zk && make

      - name: Get version from tag
        id: package-version
        run: echo "current-version=${GITHUB_REF#refs/*/zk-v}" >> $GITHUB_OUTPUT

      - name: "Release"
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-notes.md
          files: ./zk/bin/*
          name: Unchained zk Tools v${{ steps.package-version.outputs.current-version }}
